import { Client } from "pg";

// Seed data from rallygrids_seed_2026.csv.
// Usage: bun lib/db/populatedb.ts [connection-string]
const SQL = `
    DROP TABLE IF EXISTS tournaments;
    DROP TABLE IF EXISTS players;

    CREATE TABLE players (
        id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        name VARCHAR ( 255 ) NOT NULL UNIQUE,
        tour VARCHAR ( 3 ) NOT NULL CHECK (tour IN ('ATP', 'WTA')),
        country CHAR ( 3 ) NOT NULL,
        is_neutral BOOLEAN NOT NULL DEFAULT false,
        active_2026 BOOLEAN NOT NULL,
        current_rank INT,
        top50 BOOLEAN GENERATED ALWAYS AS (current_rank IS NOT NULL AND current_rank <= 50) STORED,
        notes TEXT
    );

    CREATE TABLE tournaments (
        tourn_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        name VARCHAR ( 255 ) NOT NULL,
        short_name VARCHAR ( 3 ) NOT NULL CHECK (short_name IN ('AO', 'RG', 'WIM', 'USO')),
        tour VARCHAR ( 3 ) NOT NULL CHECK (tour IN ('ATP', 'WTA')),
        year INT NOT NULL,
        -- Each round includes the players who went further, e.g. the
        -- winner is also in finalists, semifinalists and quarterfinalists.
        winner INT REFERENCES players ( id ),
        finalists INT[] NOT NULL DEFAULT '{}',
        semifinalists INT[] NOT NULL DEFAULT '{}',
        quarterfinalists INT[] NOT NULL DEFAULT '{}',
        UNIQUE (short_name, tour, year)
    );

    -- ATP and WTA top 100 as of 21 September 2026, plus notable players
    -- outside it (current_rank is NULL for anyone outside the top 100).
    INSERT INTO players (name, tour, country, is_neutral, active_2026, current_rank, notes)
    VALUES
        ('Jannik Sinner', 'ATP', 'ITA', false, true, 1, NULL),
        ('Alexander Zverev', 'ATP', 'GER', false, true, 2, 'QF at all four'),
        ('Carlos Alcaraz', 'ATP', 'ESP', false, true, 3, NULL),
        ('Ben Shelton', 'ATP', 'USA', false, true, 4, NULL),
        ('Felix Auger-Aliassime', 'ATP', 'CAN', false, true, 5, NULL),
        ('Daniil Medvedev', 'ATP', 'RUS', true, true, 6, 'top 10 with no 2026 QF; neutral flag'),
        ('Flavio Cobolli', 'ATP', 'ITA', false, true, 7, NULL),
        ('Frances Tiafoe', 'ATP', 'USA', false, true, 8, NULL),
        ('Alex de Minaur', 'ATP', 'AUS', false, true, 9, NULL),
        ('Taylor Fritz', 'ATP', 'USA', false, true, 10, NULL),
        ('Arthur Fils', 'ATP', 'FRA', false, true, 11, NULL),
        ('Novak Djokovic', 'ATP', 'SRB', false, true, 12, NULL),
        ('Learner Tien', 'ATP', 'USA', false, true, 13, NULL),
        ('Rafael Jodar', 'ATP', 'ESP', false, true, 14, NULL),
        ('Jakub Mensik', 'ATP', 'CZE', false, true, 15, NULL),
        ('Brandon Nakashima', 'ATP', 'USA', false, true, 16, NULL),
        ('Casper Ruud', 'ATP', 'NOR', false, true, 17, NULL),
        ('Tommy Paul', 'ATP', 'USA', false, true, 18, NULL),
        ('Valentin Vacherot', 'ATP', 'MON', false, true, 19, NULL),
        ('Luciano Darderi', 'ATP', 'ITA', false, true, 20, NULL),
        ('Alexander Bublik', 'ATP', 'KAZ', false, true, 21, NULL),
        ('Francisco Cerundolo', 'ATP', 'ARG', false, true, 22, NULL),
        ('Jiri Lehecka', 'ATP', 'CZE', false, true, 23, NULL),
        ('Lorenzo Musetti', 'ATP', 'ITA', false, true, 24, NULL),
        ('Andrey Rublev', 'ATP', 'RUS', true, true, 25, NULL),
        ('Karen Khachanov', 'ATP', 'RUS', true, true, 26, NULL),
        ('Alexander Blockx', 'ATP', 'BEL', false, true, 27, NULL),
        ('Joao Fonseca', 'ATP', 'BRA', false, true, 28, NULL),
        ('Alejandro Davidovich Fokina', 'ATP', 'ESP', false, true, 29, NULL),
        ('Tomas Martin Etcheverry', 'ATP', 'ARG', false, true, 30, NULL),
        ('Arthur Rinderknech', 'ATP', 'FRA', false, true, 31, NULL),
        ('Alejandro Tabilo', 'ATP', 'CHI', false, true, 32, NULL),
        ('Ugo Humbert', 'ATP', 'FRA', false, true, 33, NULL),
        ('Alex Michelsen', 'ATP', 'USA', false, true, 34, NULL),
        ('Ignacio Buse', 'ATP', 'PER', false, true, 35, NULL),
        ('Arthur Fery', 'ATP', 'GBR', false, true, 36, 'reached QF as wildcard ranked outside top 100'),
        ('Matteo Arnaldi', 'ATP', 'ITA', false, true, 37, NULL),
        ('Zizou Bergs', 'ATP', 'BEL', false, true, 38, NULL),
        ('Cameron Norrie', 'ATP', 'GBR', false, true, 39, NULL),
        ('Botic van de Zandschulp', 'ATP', 'NED', false, true, 40, NULL),
        ('Daniel Merida Aguilar', 'ATP', 'ESP', false, true, 41, NULL),
        ('Luca Van Assche', 'ATP', 'FRA', false, true, 42, NULL),
        ('Matteo Berrettini', 'ATP', 'ITA', false, true, 43, 'QF ended by retirement; ranked 105 at the time'),
        ('Stefanos Tsitsipas', 'ATP', 'GRE', false, true, 44, NULL),
        ('Mariano Navone', 'ATP', 'ARG', false, true, 45, NULL),
        ('Hubert Hurkacz', 'ATP', 'POL', false, true, 46, NULL),
        ('Raphael Collignon', 'ATP', 'BEL', false, true, 47, NULL),
        ('Nuno Borges', 'ATP', 'POR', false, true, 48, NULL),
        ('Quentin Halys', 'ATP', 'FRA', false, true, 49, NULL),
        ('Denis Shapovalov', 'ATP', 'CAN', false, true, 50, NULL),
        ('Sebastian Baez', 'ATP', 'ARG', false, true, 51, NULL),
        ('Thiago Agustin Tirante', 'ATP', 'ARG', false, true, 52, NULL),
        ('Juan Manuel Cerundolo', 'ATP', 'ARG', false, true, 53, NULL),
        ('Yannick Hanfmann', 'ATP', 'GER', false, true, 54, NULL),
        ('Tallon Griekspoor', 'ATP', 'NED', false, true, 55, NULL),
        ('Roman Andres Burruchaga', 'ATP', 'ARG', false, true, 56, NULL),
        ('Ethan Quinn', 'ATP', 'USA', false, true, 57, NULL),
        ('Adolfo Daniel Vallejo', 'ATP', 'PAR', false, true, 58, NULL),
        ('Fabian Marozsan', 'ATP', 'HUN', false, true, 59, NULL),
        ('Miomir Kecmanovic', 'ATP', 'SRB', false, true, 60, NULL),
        ('Arthur Gea', 'ATP', 'FRA', false, true, 61, NULL),
        ('Martin Landaluce', 'ATP', 'ESP', false, true, 62, NULL),
        ('Jan-Lennard Struff', 'ATP', 'GER', false, true, 63, 'QF but outside top 50'),
        ('Sebastian Korda', 'ATP', 'USA', false, true, 64, NULL),
        ('James Duckworth', 'ATP', 'AUS', false, true, 65, NULL),
        ('Jaume Munar', 'ATP', 'ESP', false, true, 66, NULL),
        ('Daniel Altmaier', 'ATP', 'GER', false, true, 67, NULL),
        ('Jaime Faria', 'ATP', 'POR', false, true, 68, NULL),
        ('Pablo Carreno Busta', 'ATP', 'ESP', false, true, 69, NULL),
        ('Corentin Moutet', 'ATP', 'FRA', false, true, 70, NULL),
        ('Vit Kopriva', 'ATP', 'CZE', false, true, 71, NULL),
        ('Facundo Diaz Acosta', 'ATP', 'ARG', false, true, 72, NULL),
        ('Kamil Majchrzak', 'ATP', 'POL', false, true, 73, NULL),
        ('Tomas Machac', 'ATP', 'CZE', false, true, 74, NULL),
        ('Camilo Ugo Carabelli', 'ATP', 'ARG', false, true, 75, NULL),
        ('Hamad Medjedovic', 'ATP', 'SRB', false, true, 76, NULL),
        ('Jenson Brooksby', 'ATP', 'USA', false, true, 77, NULL),
        ('Adrian Mannarino', 'ATP', 'FRA', false, true, 78, NULL),
        ('Marin Cilic', 'ATP', 'CRO', false, true, 79, NULL),
        ('Aleksandar Kovacevic', 'ATP', 'USA', false, true, 80, NULL),
        ('Zachary Svajda', 'ATP', 'USA', false, true, 81, NULL),
        ('Rinky Hijikata', 'ATP', 'AUS', false, true, 82, NULL),
        ('Terence Atmane', 'ATP', 'FRA', false, true, 83, NULL),
        ('Titouan Droguet', 'ATP', 'FRA', false, true, 84, NULL),
        ('Marcos Giron', 'ATP', 'USA', false, true, 85, NULL),
        ('Lorenzo Sonego', 'ATP', 'ITA', false, true, 86, NULL),
        ('Marco Trungelliti', 'ATP', 'ARG', false, true, 87, NULL),
        ('Mattia Bellucci', 'ATP', 'ITA', false, true, 88, NULL),
        ('Jan Choinski', 'ATP', 'GBR', false, true, 89, NULL),
        ('Benjamin Bonzi', 'ATP', 'FRA', false, true, 90, NULL),
        ('Aleksandar Vukic', 'ATP', 'AUS', false, true, 91, NULL),
        ('Michael Zheng', 'ATP', 'USA', false, true, 92, NULL),
        ('Sho Shimabukuro', 'ATP', 'JPN', false, true, 93, NULL),
        ('Jacob Fearnley', 'ATP', 'GBR', false, true, 94, NULL),
        ('Jesper de Jong', 'ATP', 'NED', false, true, 95, NULL),
        ('Alex Molcan', 'ATP', 'SVK', false, true, 96, NULL),
        ('Hugo Gaston', 'ATP', 'FRA', false, true, 97, NULL),
        ('Toby Samuel', 'ATP', 'GBR', false, true, 98, NULL),
        ('Adam Walton', 'ATP', 'AUS', false, true, 99, NULL),
        ('Damir Dzumhur', 'ATP', 'BIH', false, true, 100, NULL),
        ('Stan Wawrinka', 'ATP', 'SUI', false, true, NULL, 'active only via AO 2026 farewell'),
        ('Rafael Nadal', 'ATP', 'ESP', false, false, NULL, 'retired 2024'),
        ('Andy Murray', 'ATP', 'GBR', false, false, NULL, 'retired 2024'),
        ('Roger Federer', 'ATP', 'SUI', false, false, NULL, 'appeared at USO 2026 (Hall of Fame) but did not play'),
        ('Andy Roddick', 'ATP', 'USA', false, false, NULL, NULL),
        ('John Isner', 'ATP', 'USA', false, false, NULL, NULL),
        ('Elena Rybakina', 'WTA', 'KAZ', false, true, 1, NULL),
        ('Aryna Sabalenka', 'WTA', 'BLR', true, true, 2, 'neutral flag'),
        ('Jessica Pegula', 'WTA', 'USA', false, true, 3, NULL),
        ('Coco Gauff', 'WTA', 'USA', false, true, 4, NULL),
        ('Mirra Andreeva', 'WTA', 'RUS', true, true, 5, 'neutral flag'),
        ('Linda Noskova', 'WTA', 'CZE', false, true, 6, NULL),
        ('Elina Svitolina', 'WTA', 'UKR', false, true, 7, NULL),
        ('Karolina Muchova', 'WTA', 'CZE', false, true, 8, NULL),
        ('Iga Swiatek', 'WTA', 'POL', false, true, 9, NULL),
        ('Marta Kostyuk', 'WTA', 'UKR', false, true, 10, NULL),
        ('Amanda Anisimova', 'WTA', 'USA', false, true, 11, NULL),
        ('Belinda Bencic', 'WTA', 'SUI', false, true, 12, NULL),
        ('Iva Jovic', 'WTA', 'USA', false, true, 13, NULL),
        ('Diana Shnaider', 'WTA', 'RUS', true, true, 14, NULL),
        ('Victoria Mboko', 'WTA', 'CAN', false, true, 15, NULL),
        ('Sorana Cirstea', 'WTA', 'ROU', false, true, 16, NULL),
        ('Naomi Osaka', 'WTA', 'JPN', false, true, 17, NULL),
        ('Alexandra Eala', 'WTA', 'PHI', false, true, 18, NULL),
        ('Elise Mertens', 'WTA', 'BEL', false, true, 19, NULL),
        ('Jasmine Paolini', 'WTA', 'ITA', false, true, 20, NULL),
        ('Anna Kalinskaya', 'WTA', 'RUS', true, true, 21, NULL),
        ('Madison Keys', 'WTA', 'USA', false, true, 22, NULL),
        ('Emma Navarro', 'WTA', 'USA', false, true, 23, NULL),
        ('Anastasia Potapova', 'WTA', 'AUT', false, true, 24, NULL),
        ('Maja Chwalinska', 'WTA', 'POL', false, true, 25, 'reached QF as qualifier ranked 114'),
        ('Marie Bouzkova', 'WTA', 'CZE', false, true, 26, NULL),
        ('Ekaterina Alexandrova', 'WTA', 'RUS', true, true, 27, NULL),
        ('Sara Bejlek', 'WTA', 'CZE', false, true, 28, NULL),
        ('Ann Li', 'WTA', 'USA', false, true, 29, NULL),
        ('Diane Parry', 'WTA', 'FRA', false, true, 30, NULL),
        ('Leylah Fernandez', 'WTA', 'CAN', false, true, 31, NULL),
        ('Jelena Ostapenko', 'WTA', 'LAT', false, true, 32, NULL),
        ('Maria Sakkari', 'WTA', 'GRE', false, true, 33, NULL),
        ('Nikola Bartunkova', 'WTA', 'CZE', false, true, 34, NULL),
        ('Cristina Bucsa', 'WTA', 'ESP', false, true, 35, NULL),
        ('Peyton Stearns', 'WTA', 'USA', false, true, 36, NULL),
        ('Liudmila Samsonova', 'WTA', 'RUS', true, true, 37, NULL),
        ('Donna Vekic', 'WTA', 'CRO', false, true, 38, NULL),
        ('Hailey Baptiste', 'WTA', 'USA', false, true, 39, NULL),
        ('Wang Xinyu', 'WTA', 'CHN', false, true, 40, NULL),
        ('Clara Tauson', 'WTA', 'DEN', false, true, 41, NULL),
        ('Yuliia Starodubtseva', 'WTA', 'UKR', false, true, 42, NULL),
        ('Daria Snigur', 'WTA', 'UKR', false, true, 43, NULL),
        ('Barbora Krejcikova', 'WTA', 'CZE', false, true, 44, NULL),
        ('Magdalena Frech', 'WTA', 'POL', false, true, 45, NULL),
        ('Janice Tjen', 'WTA', 'INA', false, true, 46, NULL),
        ('Oleksandra Oliynykova', 'WTA', 'UKR', false, true, 47, NULL),
        ('Anhelina Kalinina', 'WTA', 'UKR', false, true, 48, NULL),
        ('Karolina Pliskova', 'WTA', 'CZE', false, true, 49, NULL),
        ('Mayar Sherif', 'WTA', 'EGY', false, true, 50, NULL),
        ('Tamara Korpatsch', 'WTA', 'GER', false, true, 51, NULL),
        ('Zheng Qinwen', 'WTA', 'CHN', false, true, 52, 'QF as qualifier; outside top 50'),
        ('Katerina Siniakova', 'WTA', 'CZE', false, true, 53, NULL),
        ('Katie Boulter', 'WTA', 'GBR', false, true, 54, NULL),
        ('Zhang Shuai', 'WTA', 'CHN', false, true, 55, NULL),
        ('Zeynep Sonmez', 'WTA', 'TUR', false, true, 56, NULL),
        ('Paula Badosa', 'WTA', 'ESP', false, true, 57, NULL),
        ('Jaqueline Cristian', 'WTA', 'ROU', false, true, 58, NULL),
        ('Lilli Tagger', 'WTA', 'AUT', false, true, 59, NULL),
        ('Kimberly Birrell', 'WTA', 'AUS', false, true, 60, NULL),
        ('Tereza Valentova', 'WTA', 'CZE', false, true, 61, NULL),
        ('Lanlana Tararudee', 'WTA', 'THA', false, true, 62, NULL),
        ('Talia Gibson', 'WTA', 'AUS', false, true, 63, NULL),
        ('Camila Osorio', 'WTA', 'COL', false, true, 64, NULL),
        ('Viktorija Golubic', 'WTA', 'SUI', false, true, 65, NULL),
        ('Elena-Gabriela Ruse', 'WTA', 'ROU', false, true, 66, NULL),
        ('Elisabetta Cocciaretto', 'WTA', 'ITA', false, true, 67, NULL),
        ('Caty McNally', 'WTA', 'USA', false, true, 68, NULL),
        ('Anna Bondar', 'WTA', 'HUN', false, true, 69, NULL),
        ('Alycia Parks', 'WTA', 'USA', false, true, 70, NULL),
        ('Ashlyn Krueger', 'WTA', 'USA', false, true, 71, NULL),
        ('McCartney Kessler', 'WTA', 'USA', false, true, 72, NULL),
        ('Kaitlin Quevedo', 'WTA', 'ESP', false, true, 73, NULL),
        ('Panna Udvardy', 'WTA', 'HUN', false, true, 74, NULL),
        ('Magda Linette', 'WTA', 'POL', false, true, 75, NULL),
        ('Petra Marcinko', 'WTA', 'CRO', false, true, 76, NULL),
        ('Kamilla Rakhimova', 'WTA', 'UZB', false, true, 77, NULL),
        ('Katie Volynets', 'WTA', 'USA', false, true, 78, NULL),
        ('Yulia Putintseva', 'WTA', 'KAZ', false, true, 79, NULL),
        ('Antonia Ruzic', 'WTA', 'CRO', false, true, 80, NULL),
        ('Tatjana Maria', 'WTA', 'GER', false, true, 81, NULL),
        ('Alina Korneeva', 'WTA', 'RUS', true, true, 82, NULL),
        ('Wang Xiyu', 'WTA', 'CHN', false, true, 83, NULL),
        ('Hanne Vandewinkel', 'WTA', 'BEL', false, true, 84, NULL),
        ('Daria Kasatkina', 'WTA', 'AUS', false, true, 85, NULL),
        ('Darja Vidmanova', 'WTA', 'CZE', false, true, 86, NULL),
        ('Anna Blinkova', 'WTA', 'FRA', false, true, 87, NULL),
        ('Maria Timofeeva', 'WTA', 'UZB', false, true, 88, NULL),
        ('Mananchaya Sawangkaew', 'WTA', 'THA', false, true, 89, NULL),
        ('Taylor Townsend', 'WTA', 'USA', false, true, 90, 'doubles #2; singles outside top 50'),
        ('Solana Sierra', 'WTA', 'ARG', false, true, 91, NULL),
        ('Renata Zarazua', 'WTA', 'MEX', false, true, 92, NULL),
        ('Jessica Bouzas Maneiro', 'WTA', 'ESP', false, true, 93, NULL),
        ('Taylah Preston', 'WTA', 'AUS', false, true, 94, NULL),
        ('Sinja Kraus', 'WTA', 'AUT', false, true, 95, NULL),
        ('Claire Liu', 'WTA', 'USA', false, true, 96, NULL),
        ('Simona Waltert', 'WTA', 'SUI', false, true, 97, NULL),
        ('Emma Raducanu', 'WTA', 'GBR', false, true, 98, NULL),
        ('Maya Joint', 'WTA', 'AUS', false, true, 99, NULL),
        ('Eva Lys', 'WTA', 'GER', false, true, 100, NULL),
        ('Venus Williams', 'WTA', 'USA', false, true, NULL, 'USO 2026 wildcard at 46; unranked'),
        ('Serena Williams', 'WTA', 'USA', false, true, NULL, 'returned at Wimbledon 2026 (lost 1R); unranked'),
        ('Maria Sharapova', 'WTA', 'RUS', false, false, NULL, 'presented USO 2026 trophy but did not play');

    -- Best 2026 Slam result for each seeded player (QF, SF, F or W).
    WITH results (player, short_name, result) AS (
      VALUES
        ('Jannik Sinner', 'AO', 'SF'),
        ('Jannik Sinner', 'WIM', 'W'),
        ('Alexander Zverev', 'AO', 'SF'),
        ('Alexander Zverev', 'RG', 'W'),
        ('Alexander Zverev', 'WIM', 'F'),
        ('Alexander Zverev', 'USO', 'W'),
        ('Carlos Alcaraz', 'AO', 'W'),
        ('Carlos Alcaraz', 'USO', 'QF'),
        ('Ben Shelton', 'AO', 'QF'),
        ('Ben Shelton', 'USO', 'F'),
        ('Flavio Cobolli', 'RG', 'F'),
        ('Flavio Cobolli', 'WIM', 'QF'),
        ('Frances Tiafoe', 'USO', 'SF'),
        ('Karen Khachanov', 'USO', 'SF'),
        ('Alexander Blockx', 'USO', 'QF'),
        ('Taylor Fritz', 'WIM', 'QF'),
        ('Felix Auger-Aliassime', 'WIM', 'QF'),
        ('Novak Djokovic', 'AO', 'F'),
        ('Novak Djokovic', 'WIM', 'SF'),
        ('Learner Tien', 'AO', 'QF'),
        ('Alex de Minaur', 'AO', 'QF'),
        ('Lorenzo Musetti', 'AO', 'QF'),
        ('Alex Michelsen', 'USO', 'QF'),
        ('Arthur Fery', 'WIM', 'SF'),
        ('Botic van de Zandschulp', 'USO', 'QF'),
        ('Matteo Berrettini', 'RG', 'QF'),
        ('Matteo Arnaldi', 'RG', 'SF'),
        ('Jakub Mensik', 'RG', 'SF'),
        ('Felix Auger-Aliassime', 'RG', 'QF'),
        ('Joao Fonseca', 'RG', 'QF'),
        ('Rafael Jodar', 'RG', 'QF'),
        ('Jan-Lennard Struff', 'WIM', 'QF'),
        ('Elena Rybakina', 'AO', 'W'),
        ('Elena Rybakina', 'USO', 'W'),
        ('Aryna Sabalenka', 'AO', 'F'),
        ('Aryna Sabalenka', 'RG', 'QF'),
        ('Aryna Sabalenka', 'USO', 'F'),
        ('Jessica Pegula', 'AO', 'SF'),
        ('Jessica Pegula', 'WIM', 'QF'),
        ('Jessica Pegula', 'USO', 'SF'),
        ('Coco Gauff', 'AO', 'QF'),
        ('Coco Gauff', 'WIM', 'SF'),
        ('Coco Gauff', 'USO', 'SF'),
        ('Mirra Andreeva', 'RG', 'W'),
        ('Diana Shnaider', 'RG', 'SF'),
        ('Marta Kostyuk', 'RG', 'SF'),
        ('Anna Kalinskaya', 'RG', 'QF'),
        ('Elina Svitolina', 'RG', 'QF'),
        ('Sorana Cirstea', 'RG', 'QF'),
        ('Mirra Andreeva', 'USO', 'QF'),
        ('Linda Noskova', 'WIM', 'W'),
        ('Linda Noskova', 'USO', 'QF'),
        ('Karolina Muchova', 'WIM', 'F'),
        ('Iga Swiatek', 'AO', 'QF'),
        ('Amanda Anisimova', 'AO', 'QF'),
        ('Iva Jovic', 'AO', 'QF'),
        ('Elina Svitolina', 'AO', 'SF'),
        ('Naomi Osaka', 'WIM', 'QF'),
        ('Marta Kostyuk', 'WIM', 'SF'),
        ('Jasmine Paolini', 'WIM', 'QF'),
        ('Elise Mertens', 'WIM', 'QF'),
        ('Emma Navarro', 'USO', 'QF'),
        ('Maja Chwalinska', 'RG', 'F'),
        ('Zheng Qinwen', 'USO', 'QF')
    )
    INSERT INTO tournaments (name, short_name, tour, year, winner, finalists, semifinalists, quarterfinalists)
    SELECT
        slams.name,
        slams.short_name,
        players.tour,
        2026,
        (array_agg(players.id) FILTER (WHERE result = 'W'))[1],
        COALESCE(array_agg(players.id) FILTER (WHERE result IN ('F', 'W')), '{}'),
        COALESCE(array_agg(players.id) FILTER (WHERE result IN ('SF', 'F', 'W')), '{}'),
        array_agg(players.id)
    FROM results
    JOIN players ON players.name = results.player
    JOIN (
      VALUES
        ('Australian Open', 'AO', 1),
        ('Roland Garros', 'RG', 2),
        ('Wimbledon', 'WIM', 3),
        ('US Open', 'USO', 4)
    ) AS slams (name, short_name, sort_order) ON slams.short_name = results.short_name
    GROUP BY slams.name, slams.short_name, slams.sort_order, players.tour
    ORDER BY slams.sort_order, players.tour;
`;

async function main() {
  console.log("seeding...");
  const client = new Client(
    process.argv[2]
      ? { connectionString: process.argv[2] }
      : {
          host: "localhost",
          user: "johnglen.siy",
          database: "rally_grids",
          port: 5432,
        },
  );
  await client.connect();
  try {
    await client.query(SQL);
  } finally {
    await client.end();
  }
  console.log("done");
}

main();
