import { Client } from "pg";

// Seed data from rallygrids_seed_2026.csv.
// Usage: bun lib/db/populatedb.ts [connection-string]
const SQL = `
    DROP TABLE IF EXISTS tournaments;
    DROP TABLE IF EXISTS players;

    CREATE TABLE players (
        id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        name VARCHAR ( 255 ) NOT NULL UNIQUE,
        tour VARCHAR ( 3 ) NOT NULL CHECK (tour IN ('ATP', 'WTA')),
        country CHAR ( 3 ) NOT NULL,
        is_neutral BOOLEAN NOT NULL DEFAULT false,
        active_2026 BOOLEAN NOT NULL,
        current_rank INT,
        top50 BOOLEAN GENERATED ALWAYS AS (current_rank IS NOT NULL AND current_rank <= 50) STORED,
        notes TEXT
    );

    CREATE TABLE tournaments (
        tourn_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        name VARCHAR ( 255 ) NOT NULL,
        short_name VARCHAR ( 3 ) NOT NULL CHECK (short_name IN ('AO', 'RG', 'WIM', 'USO')),
        tour VARCHAR ( 3 ) NOT NULL CHECK (tour IN ('ATP', 'WTA')),
        year INT NOT NULL,
        -- Each round includes the players who went further, e.g. the
        -- winner is also in finalists, semifinalists and quarterfinalists.
        winner INT REFERENCES players ( id ),
        finalists INT[] NOT NULL DEFAULT '{}',
        semifinalists INT[] NOT NULL DEFAULT '{}',
        quarterfinalists INT[] NOT NULL DEFAULT '{}',
        UNIQUE (short_name, tour, year)
    );

    -- ATP and WTA top 100 as of 21 September 2026, plus notable players
    -- outside it (current_rank is NULL for anyone outside the top 100).
    INSERT INTO players (name, tour, country, is_neutral, active_2026, current_rank, notes)
    VALUES
        ('Jannik Sinner', 'ATP', 'ITA', false, true, 1, NULL),
        ('Alexander Zverev', 'ATP', 'GER', false, true, 2, 'QF at all four'),
        ('Carlos Alcaraz', 'ATP', 'ESP', false, true, 3, NULL),
        ('Ben Shelton', 'ATP', 'USA', false, true, 4, NULL),
        ('Felix Auger-Aliassime', 'ATP', 'CAN', false, true, 5, NULL),
        ('Daniil Medvedev', 'ATP', 'RUS', true, true, 6, 'top 10 with no 2026 QF; neutral flag'),
        ('Flavio Cobolli', 'ATP', 'ITA', false, true, 7, NULL),
        ('Frances Tiafoe', 'ATP', 'USA', false, true, 8, NULL),
        ('Alex de Minaur', 'ATP', 'AUS', false, true, 9, NULL),
        ('Taylor Fritz', 'ATP', 'USA', false, true, 10, NULL),
        ('Arthur Fils', 'ATP', 'FRA', false, true, 11, NULL),
        ('Novak Djokovic', 'ATP', 'SRB', false, true, 12, NULL),
        ('Learner Tien', 'ATP', 'USA', false, true, 13, NULL),
        ('Rafael Jodar', 'ATP', 'ESP', false, true, 14, NULL),
        ('Jakub Mensik', 'ATP', 'CZE', false, true, 15, NULL),
        ('Brandon Nakashima', 'ATP', 'USA', false, true, 16, NULL),
        ('Casper Ruud', 'ATP', 'NOR', false, true, 17, NULL),
        ('Tommy Paul', 'ATP', 'USA', false, true, 18, NULL),
        ('Valentin Vacherot', 'ATP', 'MON', false, true, 19, NULL),
        ('Luciano Darderi', 'ATP', 'ITA', false, true, 20, NULL),
        ('Alexander Bublik', 'ATP', 'KAZ', false, true, 21, NULL),
        ('Francisco Cerundolo', 'ATP', 'ARG', false, true, 22, NULL),
        ('Jiri Lehecka', 'ATP', 'CZE', false, true, 23, NULL),
        ('Lorenzo Musetti', 'ATP', 'ITA', false, true, 24, NULL),
        ('Andrey Rublev', 'ATP', 'RUS', true, true, 25, NULL),
        ('Karen Khachanov', 'ATP', 'RUS', true, true, 26, NULL),
        ('Alexander Blockx', 'ATP', 'BEL', false, true, 27, NULL),
        ('Joao Fonseca', 'ATP', 'BRA', false, true, 28, NULL),
        ('Alejandro Davidovich Fokina', 'ATP', 'ESP', false, true, 29, NULL),
        ('Tomas Martin Etcheverry', 'ATP', 'ARG', false, true, 30, NULL),
        ('Arthur Rinderknech', 'ATP', 'FRA', false, true, 31, NULL),
        ('Alejandro Tabilo', 'ATP', 'CHI', false, true, 32, NULL),
        ('Ugo Humbert', 'ATP', 'FRA', false, true, 33, NULL),
        ('Alex Michelsen', 'ATP', 'USA', false, true, 34, NULL),
        ('Ignacio Buse', 'ATP', 'PER', false, true, 35, NULL),
        ('Arthur Fery', 'ATP', 'GBR', false, true, 36, 'reached QF as wildcard ranked outside top 100'),
        ('Matteo Arnaldi', 'ATP', 'ITA', false, true, 37, NULL),
        ('Zizou Bergs', 'ATP', 'BEL', false, true, 38, NULL),
        ('Cameron Norrie', 'ATP', 'GBR', false, true, 39, NULL),
        ('Botic van de Zandschulp', 'ATP', 'NED', false, true, 40, NULL),
        ('Daniel Merida Aguilar', 'ATP', 'ESP', false, true, 41, NULL),
        ('Luca Van Assche', 'ATP', 'FRA', false, true, 42, NULL),
        ('Matteo Berrettini', 'ATP', 'ITA', false, true, 43, 'QF ended by retirement; ranked 105 at the time'),
        ('Stefanos Tsitsipas', 'ATP', 'GRE', false, true, 44, NULL),
        ('Mariano Navone', 'ATP', 'ARG', false, true, 45, NULL),
        ('Hubert Hurkacz', 'ATP', 'POL', false, true, 46, NULL),
        ('Raphael Collignon', 'ATP', 'BEL', false, true, 47, NULL),
        ('Nuno Borges', 'ATP', 'POR', false, true, 48, NULL),
        ('Quentin Halys', 'ATP', 'FRA', false, true, 49, NULL),
        ('Denis Shapovalov', 'ATP', 'CAN', false, true, 50, NULL),
        ('Sebastian Baez', 'ATP', 'ARG', false, true, 51, NULL),
        ('Thiago Agustin Tirante', 'ATP', 'ARG', false, true, 52, NULL),
        ('Juan Manuel Cerundolo', 'ATP', 'ARG', false, true, 53, NULL),
        ('Yannick Hanfmann', 'ATP', 'GER', false, true, 54, NULL),
        ('Tallon Griekspoor', 'ATP', 'NED', false, true, 55, NULL),
        ('Roman Andres Burruchaga', 'ATP', 'ARG', false, true, 56, NULL),
        ('Ethan Quinn', 'ATP', 'USA', false, true, 57, NULL),
        ('Adolfo Daniel Vallejo', 'ATP', 'PAR', false, true, 58, NULL),
        ('Fabian Marozsan', 'ATP', 'HUN', false, true, 59, NULL),
        ('Miomir Kecmanovic', 'ATP', 'SRB', false, true, 60, NULL),
        ('Arthur Gea', 'ATP', 'FRA', false, true, 61, NULL),
        ('Martin Landaluce', 'ATP', 'ESP', false, true, 62, NULL),
        ('Jan-Lennard Struff', 'ATP', 'GER', false, true, 63, 'QF but outside top 50'),
        ('Sebastian Korda', 'ATP', 'USA', false, true, 64, NULL),
        ('James Duckworth', 'ATP', 'AUS', false, true, 65, NULL),
        ('Jaume Munar', 'ATP', 'ESP', false, true, 66, NULL),
        ('Daniel Altmaier', 'ATP', 'GER', false, true, 67, NULL),
        ('Jaime Faria', 'ATP', 'POR', false, true, 68, NULL),
        ('Pablo Carreno Busta', 'ATP', 'ESP', false, true, 69, NULL),
        ('Corentin Moutet', 'ATP', 'FRA', false, true, 70, NULL),
        ('Vit Kopriva', 'ATP', 'CZE', false, true, 71, NULL),
        ('Facundo Diaz Acosta', 'ATP', 'ARG', false, true, 72, NULL),
        ('Kamil Majchrzak', 'ATP', 'POL', false, true, 73, NULL),
        ('Tomas Machac', 'ATP', 'CZE', false, true, 74, NULL),
        ('Camilo Ugo Carabelli', 'ATP', 'ARG', false, true, 75, NULL),
        ('Hamad Medjedovic', 'ATP', 'SRB', false, true, 76, NULL),
        ('Jenson Brooksby', 'ATP', 'USA', false, true, 77, NULL),
        ('Adrian Mannarino', 'ATP', 'FRA', false, true, 78, NULL),
        ('Marin Cilic', 'ATP', 'CRO', false, true, 79, NULL),
        ('Aleksandar Kovacevic', 'ATP', 'USA', false, true, 80, NULL),
        ('Zachary Svajda', 'ATP', 'USA', false, true, 81, NULL),
        ('Rinky Hijikata', 'ATP', 'AUS', false, true, 82, NULL),
        ('Terence Atmane', 'ATP', 'FRA', false, true, 83, NULL),
        ('Titouan Droguet', 'ATP', 'FRA', false, true, 84, NULL),
        ('Marcos Giron', 'ATP', 'USA', false, true, 85, NULL),
        ('Lorenzo Sonego', 'ATP', 'ITA', false, true, 86, NULL),
        ('Marco Trungelliti', 'ATP', 'ARG', false, true, 87, NULL),
        ('Mattia Bellucci', 'ATP', 'ITA', false, true, 88, NULL),
        ('Jan Choinski', 'ATP', 'GBR', false, true, 89, NULL),
        ('Benjamin Bonzi', 'ATP', 'FRA', false, true, 90, NULL),
        ('Aleksandar Vukic', 'ATP', 'AUS', false, true, 91, NULL),
        ('Michael Zheng', 'ATP', 'USA', false, true, 92, NULL),
        ('Sho Shimabukuro', 'ATP', 'JPN', false, true, 93, NULL),
        ('Jacob Fearnley', 'ATP', 'GBR', false, true, 94, NULL),
        ('Jesper de Jong', 'ATP', 'NED', false, true, 95, NULL),
        ('Alex Molcan', 'ATP', 'SVK', false, true, 96, NULL),
        ('Hugo Gaston', 'ATP', 'FRA', false, true, 97, NULL),
        ('Toby Samuel', 'ATP', 'GBR', false, true, 98, NULL),
        ('Adam Walton', 'ATP', 'AUS', false, true, 99, NULL),
        ('Damir Dzumhur', 'ATP', 'BIH', false, true, 100, NULL),
        ('Stan Wawrinka', 'ATP', 'SUI', false, true, NULL, 'active only via AO 2026 farewell'),
        ('Rafael Nadal', 'ATP', 'ESP', false, false, NULL, 'retired 2024'),
        ('Andy Murray', 'ATP', 'GBR', false, false, NULL, 'retired 2024'),
        ('Roger Federer', 'ATP', 'SUI', false, false, NULL, 'appeared at USO 2026 (Hall of Fame) but did not play'),
        ('Andy Roddick', 'ATP', 'USA', false, false, NULL, NULL),
        ('John Isner', 'ATP', 'USA', false, false, NULL, NULL),
        -- ATP year-end top 51-100 for 2000, for the headshot picker.
        ('Albert Portas', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #51 in 2000'),
        ('Andreas Vinciguerra', 'ATP', 'SWE', false, false, NULL, 'ATP year-end #52 in 2000'),
        ('Jiri Novak', 'ATP', 'CZE', false, false, NULL, 'ATP year-end #53 in 2000'),
        ('Stefan Koubek', 'ATP', 'AUT', false, false, NULL, 'ATP year-end #54 in 2000'),
        ('Todd Martin', 'ATP', 'USA', false, false, NULL, 'ATP year-end #55 in 2000'),
        ('Alex Calatrava', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #56 in 2000'),
        ('Karim Alami', 'ATP', 'MAR', false, false, NULL, 'ATP year-end #57 in 2000'),
        ('Andrei Medvedev', 'ATP', 'UKR', false, false, NULL, 'ATP year-end #58 in 2000'),
        ('Harel Levy', 'ATP', 'ISR', false, false, NULL, 'ATP year-end #59 in 2000'),
        ('Arnaud Di Pasquale', 'ATP', 'FRA', false, false, NULL, 'ATP year-end #60 in 2000'),
        ('Mariano Zabaleta', 'ATP', 'ARG', false, false, NULL, 'ATP year-end #61 in 2000'),
        ('Agustin Calleri', 'ATP', 'ARG', false, false, NULL, 'ATP year-end #62 in 2000'),
        ('Juan Ignacio Chela', 'ATP', 'ARG', false, false, NULL, 'ATP year-end #63 in 2000'),
        ('Slava Dosedel', 'ATP', 'CZE', false, false, NULL, 'ATP year-end #64 in 2000'),
        ('Davide Sanguinetti', 'ATP', 'ITA', false, false, NULL, 'ATP year-end #65 in 2000'),
        ('Jason Stoltenberg', 'ATP', 'AUS', false, false, NULL, 'ATP year-end #66 in 2000'),
        ('Olivier Rochus', 'ATP', 'BEL', false, false, NULL, 'ATP year-end #67 in 2000'),
        ('Chris Woodruff', 'ATP', 'USA', false, false, NULL, 'ATP year-end #68 in 2000'),
        ('Greg Rusedski', 'ATP', 'GBR', false, false, NULL, 'ATP year-end #69 in 2000'),
        ('Julien Boutter', 'ATP', 'FRA', false, false, NULL, 'ATP year-end #70 in 2000'),
        ('Juan Balcells', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #71 in 2000'),
        ('Markus Hantschk', 'ATP', 'GER', false, false, NULL, 'ATP year-end #72 in 2000'),
        ('Karol Kucera', 'ATP', 'SVK', false, false, NULL, 'ATP year-end #73 in 2000'),
        ('Magnus Larsson', 'ATP', 'SWE', false, false, NULL, 'ATP year-end #74 in 2000'),
        ('Christophe Rochus', 'ATP', 'BEL', false, false, NULL, 'ATP year-end #75 in 2000'),
        ('Bohdan Ulihrach', 'ATP', 'CZE', false, false, NULL, 'ATP year-end #76 in 2000'),
        ('Jiri Vanek', 'ATP', 'CZE', false, false, NULL, 'ATP year-end #77 in 2000'),
        ('Martin Damm', 'ATP', 'CZE', false, false, NULL, 'ATP year-end #78 in 2000'),
        ('Paul Goldstein', 'ATP', 'USA', false, false, NULL, 'ATP year-end #79 in 2000'),
        ('Mikael Tillstrom', 'ATP', 'SWE', false, false, NULL, 'ATP year-end #80 in 2000'),
        ('Alberto Martin', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #81 in 2000'),
        ('Magnus Gustafsson', 'ATP', 'SWE', false, false, NULL, 'ATP year-end #82 in 2000'),
        ('Wayne Arthurs', 'ATP', 'AUS', false, false, NULL, 'ATP year-end #83 in 2000'),
        ('Richard Fromberg', 'ATP', 'AUS', false, false, NULL, 'ATP year-end #84 in 2000'),
        ('Sergi Bruguera', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #85 in 2000'),
        ('Alexander Popp', 'ATP', 'GER', false, false, NULL, 'ATP year-end #86 in 2000'),
        ('Nicolas Massu', 'ATP', 'CHI', false, false, NULL, 'ATP year-end #87 in 2000'),
        ('Guillermo Coria', 'ATP', 'ARG', false, false, NULL, 'ATP year-end #88 in 2000'),
        ('David Sanchez', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #89 in 2000'),
        ('Ivan Ljubicic', 'ATP', 'CRO', false, false, NULL, 'ATP year-end #90 in 2000'),
        ('Hyung-taik Lee', 'ATP', 'KOR', false, false, NULL, 'ATP year-end #91 in 2000'),
        ('German Puentes', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #92 in 2000'),
        ('Michel Kratochvil', 'ATP', 'SUI', false, false, NULL, 'ATP year-end #93 in 2000'),
        ('Sargis Sargsian', 'ATP', 'ARM', false, false, NULL, 'ATP year-end #94 in 2000'),
        ('Raemon Sluiter', 'ATP', 'NED', false, false, NULL, 'ATP year-end #95 in 2000'),
        ('Michal Tabara', 'ATP', 'CZE', false, false, NULL, 'ATP year-end #96 in 2000'),
        ('Justin Gimelstob', 'ATP', 'USA', false, false, NULL, 'ATP year-end #97 in 2000'),
        ('Daniel Elsner', 'ATP', 'GER', false, false, NULL, 'ATP year-end #98 in 2000'),
        ('Felix Mantilla', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #99 in 2000'),
        ('Fernando Meligeni', 'ATP', 'BRA', false, false, NULL, 'ATP year-end #100 in 2000'),
        -- ATP year-end top 100 for 2010, for the headshot picker.
        ('Robin Soderling', 'ATP', 'SWE', false, false, NULL, 'ATP year-end #5 in 2010'),
        ('Tomas Berdych', 'ATP', 'CZE', false, false, NULL, 'ATP year-end #6 in 2010'),
        ('David Ferrer', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #7 in 2010'),
        ('Fernando Verdasco', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #9 in 2010'),
        ('Mikhail Youzhny', 'ATP', 'RUS', false, false, NULL, 'ATP year-end #10 in 2010'),
        ('Jurgen Melzer', 'ATP', 'AUT', false, false, NULL, 'ATP year-end #11 in 2010'),
        ('Gael Monfils', 'ATP', 'FRA', false, false, NULL, 'ATP year-end #12 in 2010'),
        ('Jo-Wilfried Tsonga', 'ATP', 'FRA', false, false, NULL, 'ATP year-end #13 in 2010'),
        ('Nicolas Almagro', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #15 in 2010'),
        ('Mardy Fish', 'ATP', 'USA', false, false, NULL, 'ATP year-end #16 in 2010'),
        ('Sam Querrey', 'ATP', 'USA', false, false, NULL, 'ATP year-end #18 in 2010'),
        ('Marcos Baghdatis', 'ATP', 'CYP', false, false, NULL, 'ATP year-end #20 in 2010'),
        ('Nikolay Davydenko', 'ATP', 'RUS', false, false, NULL, 'ATP year-end #22 in 2010'),
        ('Michael Llodra', 'ATP', 'FRA', false, false, NULL, 'ATP year-end #23 in 2010'),
        ('Ernests Gulbis', 'ATP', 'LAT', false, false, NULL, 'ATP year-end #24 in 2010'),
        ('Albert Montanes', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #25 in 2010'),
        ('Juan Monaco', 'ATP', 'ARG', false, false, NULL, 'ATP year-end #26 in 2010'),
        ('David Nalbandian', 'ATP', 'ARG', false, false, NULL, 'ATP year-end #27 in 2010'),
        ('Viktor Troicki', 'ATP', 'SRB', false, false, NULL, 'ATP year-end #28 in 2010'),
        ('Juan Carlos Ferrero', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #29 in 2010'),
        ('Richard Gasquet', 'ATP', 'FRA', false, false, NULL, 'ATP year-end #30 in 2010'),
        ('Thomaz Bellucci', 'ATP', 'BRA', false, false, NULL, 'ATP year-end #31 in 2010'),
        ('Feliciano Lopez', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #32 in 2010'),
        ('Guillermo Garcia-Lopez', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #33 in 2010'),
        ('Philipp Kohlschreiber', 'ATP', 'GER', false, false, NULL, 'ATP year-end #34 in 2010'),
        ('Yen-Hsun Lu', 'ATP', 'TPE', false, false, NULL, 'ATP year-end #35 in 2010'),
        ('Andrey Golubev', 'ATP', 'KAZ', false, false, NULL, 'ATP year-end #36 in 2010'),
        ('Florian Mayer', 'ATP', 'GER', false, false, NULL, 'ATP year-end #37 in 2010'),
        ('Jarkko Nieminen', 'ATP', 'FIN', false, false, NULL, 'ATP year-end #39 in 2010'),
        ('Denis Istomin', 'ATP', 'UZB', false, false, NULL, 'ATP year-end #40 in 2010'),
        ('Gilles Simon', 'ATP', 'FRA', false, false, NULL, 'ATP year-end #41 in 2010'),
        ('Marcel Granollers', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #42 in 2010'),
        ('Thiemo de Bakker', 'ATP', 'NED', false, false, NULL, 'ATP year-end #43 in 2010'),
        ('Julien Benneteau', 'ATP', 'FRA', false, false, NULL, 'ATP year-end #44 in 2010'),
        ('Jeremy Chardy', 'ATP', 'FRA', false, false, NULL, 'ATP year-end #45 in 2010'),
        ('Sergiy Stakhovsky', 'ATP', 'UKR', false, false, NULL, 'ATP year-end #46 in 2010'),
        ('Potito Starace', 'ATP', 'ITA', false, false, NULL, 'ATP year-end #47 in 2010'),
        ('Aleksandr Dolgopolov', 'ATP', 'UKR', false, false, NULL, 'ATP year-end #48 in 2010'),
        ('Janko Tipsarevic', 'ATP', 'SRB', false, false, NULL, 'ATP year-end #49 in 2010'),
        ('Tommy Robredo', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #50 in 2010'),
        ('Victor Hanescu', 'ATP', 'ROU', false, false, NULL, 'ATP year-end #51 in 2010'),
        ('Andreas Seppi', 'ATP', 'ITA', false, false, NULL, 'ATP year-end #52 in 2010'),
        ('Benjamin Becker', 'ATP', 'GER', false, false, NULL, 'ATP year-end #53 in 2010'),
        ('Lleyton Hewitt', 'ATP', 'AUS', false, false, NULL, 'ATP year-end #54 in 2010'),
        ('Fabio Fognini', 'ATP', 'ITA', false, false, NULL, 'ATP year-end #55 in 2010'),
        ('Daniel Gimeno-Traver', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #56 in 2010'),
        ('Philipp Petzschner', 'ATP', 'GER', false, false, NULL, 'ATP year-end #57 in 2010'),
        ('Michael Berrer', 'ATP', 'GER', false, false, NULL, 'ATP year-end #58 in 2010'),
        ('Mikhail Kukushkin', 'ATP', 'KAZ', false, false, NULL, 'ATP year-end #59 in 2010'),
        ('Xavier Malisse', 'ATP', 'BEL', false, false, NULL, 'ATP year-end #60 in 2010'),
        ('Kevin Anderson', 'ATP', 'RSA', false, false, NULL, 'ATP year-end #61 in 2010'),
        ('Radek Stepanek', 'ATP', 'CZE', false, false, NULL, 'ATP year-end #62 in 2010'),
        ('Pablo Cuevas', 'ATP', 'URU', false, false, NULL, 'ATP year-end #63 in 2010'),
        ('Santiago Giraldo', 'ATP', 'COL', false, false, NULL, 'ATP year-end #64 in 2010'),
        ('Robin Haase', 'ATP', 'NED', false, false, NULL, 'ATP year-end #65 in 2010'),
        ('Carlos Berlocq', 'ATP', 'ARG', false, false, NULL, 'ATP year-end #66 in 2010'),
        ('Tobias Kamke', 'ATP', 'GER', false, false, NULL, 'ATP year-end #67 in 2010'),
        ('Fernando Gonzalez', 'ATP', 'CHI', false, false, NULL, 'ATP year-end #68 in 2010'),
        ('Florent Serra', 'ATP', 'FRA', false, false, NULL, 'ATP year-end #69 in 2010'),
        ('Lukasz Kubot', 'ATP', 'POL', false, false, NULL, 'ATP year-end #70 in 2010'),
        ('Pablo Andujar', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #71 in 2010'),
        ('Pere Riba', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #72 in 2010'),
        ('Ivo Karlovic', 'ATP', 'CRO', false, false, NULL, 'ATP year-end #73 in 2010'),
        ('Eduardo Schwank', 'ATP', 'ARG', false, false, NULL, 'ATP year-end #74 in 2010'),
        ('Dudi Sela', 'ATP', 'ISR', false, false, NULL, 'ATP year-end #75 in 2010'),
        ('Ricardo Mello', 'ATP', 'BRA', false, false, NULL, 'ATP year-end #76 in 2010'),
        ('Ruben Ramirez Hidalgo', 'ATP', 'ESP', false, false, NULL, 'ATP year-end #77 in 2010'),
        ('Arnaud Clement', 'ATP', 'FRA', false, false, NULL, 'ATP year-end #78 in 2010'),
        ('Igor Andreev', 'ATP', 'RUS', false, false, NULL, 'ATP year-end #79 in 2010'),
        ('Teimuraz Gabashvili', 'ATP', 'RUS', false, false, NULL, 'ATP year-end #80 in 2010'),
        ('Illya Marchenko', 'ATP', 'UKR', false, false, NULL, 'ATP year-end #81 in 2010'),
        ('Mischa Zverev', 'ATP', 'GER', false, false, NULL, 'ATP year-end #82 in 2010'),
        ('Rainer Schuettler', 'ATP', 'GER', false, false, NULL, 'ATP year-end #84 in 2010'),
        ('Brian Dabul', 'ATP', 'ARG', false, false, NULL, 'ATP year-end #85 in 2010'),
        ('Michal Przysiezny', 'ATP', 'POL', false, false, NULL, 'ATP year-end #86 in 2010'),
        ('Ricardas Berankis', 'ATP', 'LTU', false, false, NULL, 'ATP year-end #87 in 2010'),
        ('Ivan Dodig', 'ATP', 'CRO', false, false, NULL, 'ATP year-end #88 in 2010'),
        ('Lukas Lacko', 'ATP', 'SVK', false, false, NULL, 'ATP year-end #89 in 2010'),
        ('Marsel Ilhan', 'ATP', 'TUR', false, false, NULL, 'ATP year-end #90 in 2010'),
        ('Filippo Volandri', 'ATP', 'ITA', false, false, NULL, 'ATP year-end #91 in 2010'),
        ('Dustin Brown', 'ATP', 'GER', false, false, NULL, 'ATP year-end #92 in 2010'),
        ('Rui Machado', 'ATP', 'POR', false, false, NULL, 'ATP year-end #93 in 2010'),
        ('Leonardo Mayer', 'ATP', 'ARG', false, false, NULL, 'ATP year-end #94 in 2010'),
        ('Jan Hajek', 'ATP', 'CZE', false, false, NULL, 'ATP year-end #95 in 2010'),
        ('Marcos Daniel', 'ATP', 'BRA', false, false, NULL, 'ATP year-end #96 in 2010'),
        ('Paul-Henri Mathieu', 'ATP', 'FRA', false, false, NULL, 'ATP year-end #97 in 2010'),
        ('Kei Nishikori', 'ATP', 'JPN', false, false, NULL, 'ATP year-end #98 in 2010'),
        ('Michael Russell', 'ATP', 'USA', false, false, NULL, 'ATP year-end #99 in 2010'),
        ('Igor Kunitsyn', 'ATP', 'RUS', false, false, NULL, 'ATP year-end #100 in 2010'),
        -- Open Era men's top 50 by Grand Slam singles titles, then finals (ties
        -- at #50 included), for the headshot picker.
        ('Pete Sampras', 'ATP', 'USA', false, false, NULL, 'Open Era Slam titles: 14 (finals: 18); all-time #4'),
        ('Bjorn Borg', 'ATP', 'SWE', false, false, NULL, 'Open Era Slam titles: 11 (finals: 16); all-time #5'),
        ('Ivan Lendl', 'ATP', 'TCH', false, false, NULL, 'Open Era Slam titles: 8 (finals: 19); all-time #6'),
        ('Andre Agassi', 'ATP', 'USA', false, false, NULL, 'Open Era Slam titles: 8 (finals: 15); all-time #7'),
        ('Jimmy Connors', 'ATP', 'USA', false, false, NULL, 'Open Era Slam titles: 8 (finals: 15); all-time #8'),
        ('John McEnroe', 'ATP', 'USA', false, false, NULL, 'Open Era Slam titles: 7 (finals: 11); all-time #9'),
        ('Mats Wilander', 'ATP', 'SWE', false, false, NULL, 'Open Era Slam titles: 7 (finals: 11); all-time #10'),
        ('Stefan Edberg', 'ATP', 'SWE', false, false, NULL, 'Open Era Slam titles: 6 (finals: 11); all-time #12'),
        ('Boris Becker', 'ATP', 'GER', false, false, NULL, 'Open Era Slam titles: 6 (finals: 10); all-time #13'),
        ('John Newcombe', 'ATP', 'AUS', false, false, NULL, 'Open Era Slam titles: 5 (finals: 7); all-time #15'),
        ('Rod Laver', 'ATP', 'AUS', false, false, NULL, 'Open Era Slam titles: 5 (finals: 6); all-time #16'),
        ('Guillermo Vilas', 'ATP', 'ARG', false, false, NULL, 'Open Era Slam titles: 4 (finals: 8); all-time #17'),
        ('Ken Rosewall', 'ATP', 'AUS', false, false, NULL, 'Open Era Slam titles: 4 (finals: 8); all-time #18'),
        ('Jim Courier', 'ATP', 'USA', false, false, NULL, 'Open Era Slam titles: 4 (finals: 7); all-time #19'),
        ('Arthur Ashe', 'ATP', 'USA', false, false, NULL, 'Open Era Slam titles: 3 (finals: 5); all-time #21'),
        ('Jan Kodes', 'ATP', 'TCH', false, false, NULL, 'Open Era Slam titles: 3 (finals: 5); all-time #22'),
        ('Gustavo Kuerten', 'ATP', 'BRA', false, false, NULL, 'Open Era Slam titles: 3 (finals: 3); all-time #24'),
        ('Ilie Nastase', 'ATP', 'ROU', false, false, NULL, 'Open Era Slam titles: 2 (finals: 5); all-time #26'),
        ('Marat Safin', 'ATP', 'RUS', false, false, NULL, 'Open Era Slam titles: 2 (finals: 4); all-time #28'),
        ('Patrick Rafter', 'ATP', 'AUS', false, false, NULL, 'Open Era Slam titles: 2 (finals: 4); all-time #29'),
        ('Stan Smith', 'ATP', 'USA', false, false, NULL, 'Open Era Slam titles: 2 (finals: 3); all-time #31'),
        ('Yevgeny Kafelnikov', 'ATP', 'RUS', false, false, NULL, 'Open Era Slam titles: 2 (finals: 3); all-time #32'),
        ('Johan Kriek', 'ATP', 'RSA', false, false, NULL, 'Open Era Slam titles: 2 (finals: 2); all-time #33'),
        ('Dominic Thiem', 'ATP', 'AUT', false, false, NULL, 'Open Era Slam titles: 1 (finals: 4); all-time #36'),
        ('Goran Ivanisevic', 'ATP', 'CRO', false, false, NULL, 'Open Era Slam titles: 1 (finals: 4); all-time #37'),
        ('Michael Chang', 'ATP', 'USA', false, false, NULL, 'Open Era Slam titles: 1 (finals: 4); all-time #38'),
        ('Michael Stich', 'ATP', 'GER', false, false, NULL, 'Open Era Slam titles: 1 (finals: 3); all-time #41'),
        ('Pat Cash', 'ATP', 'AUS', false, false, NULL, 'Open Era Slam titles: 1 (finals: 3); all-time #42'),
        ('Vitas Gerulaitis', 'ATP', 'USA', false, false, NULL, 'Open Era Slam titles: 1 (finals: 3); all-time #43'),
        ('Andres Gimeno', 'ATP', 'ESP', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #44'),
        ('Carlos Moya', 'ATP', 'ESP', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #45'),
        ('Juan Martin del Potro', 'ATP', 'ARG', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #46'),
        ('Manuel Orantes', 'ATP', 'ESP', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #47'),
        ('Petr Korda', 'ATP', 'TCH', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #48'),
        ('Roscoe Tanner', 'ATP', 'USA', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #49'),
        ('Adriano Panatta', 'ATP', 'ITA', false, false, NULL, 'Open Era Slam titles: 1 (finals: 1); all-time #50'),
        ('Albert Costa', 'ATP', 'ESP', false, false, NULL, 'Open Era Slam titles: 1 (finals: 1); all-time #51'),
        ('Andres Gomez', 'ATP', 'ECU', false, false, NULL, 'Open Era Slam titles: 1 (finals: 1); all-time #52'),
        ('Brian Teacher', 'ATP', 'USA', false, false, NULL, 'Open Era Slam titles: 1 (finals: 1); all-time #53'),
        ('Gaston Gaudio', 'ATP', 'ARG', false, false, NULL, 'Open Era Slam titles: 1 (finals: 1); all-time #54'),
        ('Mark Edmondson', 'ATP', 'AUS', false, false, NULL, 'Open Era Slam titles: 1 (finals: 1); all-time #55'),
        ('Richard Krajicek', 'ATP', 'NED', false, false, NULL, 'Open Era Slam titles: 1 (finals: 1); all-time #56'),
        ('Thomas Johansson', 'ATP', 'SWE', false, false, NULL, 'Open Era Slam titles: 1 (finals: 1); all-time #57'),
        ('Thomas Muster', 'ATP', 'AUT', false, false, NULL, 'Open Era Slam titles: 1 (finals: 1); all-time #58'),
        ('Yannick Noah', 'ATP', 'FRA', false, false, NULL, 'Open Era Slam titles: 1 (finals: 1); all-time #59'),
        ('Elena Rybakina', 'WTA', 'KAZ', false, true, 1, NULL),
        ('Aryna Sabalenka', 'WTA', 'BLR', true, true, 2, 'neutral flag'),
        ('Jessica Pegula', 'WTA', 'USA', false, true, 3, NULL),
        ('Coco Gauff', 'WTA', 'USA', false, true, 4, NULL),
        ('Mirra Andreeva', 'WTA', 'RUS', true, true, 5, 'neutral flag'),
        ('Linda Noskova', 'WTA', 'CZE', false, true, 6, NULL),
        ('Elina Svitolina', 'WTA', 'UKR', false, true, 7, NULL),
        ('Karolina Muchova', 'WTA', 'CZE', false, true, 8, NULL),
        ('Iga Swiatek', 'WTA', 'POL', false, true, 9, NULL),
        ('Marta Kostyuk', 'WTA', 'UKR', false, true, 10, NULL),
        ('Amanda Anisimova', 'WTA', 'USA', false, true, 11, NULL),
        ('Belinda Bencic', 'WTA', 'SUI', false, true, 12, NULL),
        ('Iva Jovic', 'WTA', 'USA', false, true, 13, NULL),
        ('Diana Shnaider', 'WTA', 'RUS', true, true, 14, NULL),
        ('Victoria Mboko', 'WTA', 'CAN', false, true, 15, NULL),
        ('Sorana Cirstea', 'WTA', 'ROU', false, true, 16, NULL),
        ('Naomi Osaka', 'WTA', 'JPN', false, true, 17, NULL),
        ('Alexandra Eala', 'WTA', 'PHI', false, true, 18, NULL),
        ('Elise Mertens', 'WTA', 'BEL', false, true, 19, NULL),
        ('Jasmine Paolini', 'WTA', 'ITA', false, true, 20, NULL),
        ('Anna Kalinskaya', 'WTA', 'RUS', true, true, 21, NULL),
        ('Madison Keys', 'WTA', 'USA', false, true, 22, NULL),
        ('Emma Navarro', 'WTA', 'USA', false, true, 23, NULL),
        ('Anastasia Potapova', 'WTA', 'AUT', false, true, 24, NULL),
        ('Maja Chwalinska', 'WTA', 'POL', false, true, 25, 'reached QF as qualifier ranked 114'),
        ('Marie Bouzkova', 'WTA', 'CZE', false, true, 26, NULL),
        ('Ekaterina Alexandrova', 'WTA', 'RUS', true, true, 27, NULL),
        ('Sara Bejlek', 'WTA', 'CZE', false, true, 28, NULL),
        ('Ann Li', 'WTA', 'USA', false, true, 29, NULL),
        ('Diane Parry', 'WTA', 'FRA', false, true, 30, NULL),
        ('Leylah Fernandez', 'WTA', 'CAN', false, true, 31, NULL),
        ('Jelena Ostapenko', 'WTA', 'LAT', false, true, 32, NULL),
        ('Maria Sakkari', 'WTA', 'GRE', false, true, 33, NULL),
        ('Nikola Bartunkova', 'WTA', 'CZE', false, true, 34, NULL),
        ('Cristina Bucsa', 'WTA', 'ESP', false, true, 35, NULL),
        ('Peyton Stearns', 'WTA', 'USA', false, true, 36, NULL),
        ('Liudmila Samsonova', 'WTA', 'RUS', true, true, 37, NULL),
        ('Donna Vekic', 'WTA', 'CRO', false, true, 38, NULL),
        ('Hailey Baptiste', 'WTA', 'USA', false, true, 39, NULL),
        ('Wang Xinyu', 'WTA', 'CHN', false, true, 40, NULL),
        ('Clara Tauson', 'WTA', 'DEN', false, true, 41, NULL),
        ('Yuliia Starodubtseva', 'WTA', 'UKR', false, true, 42, NULL),
        ('Daria Snigur', 'WTA', 'UKR', false, true, 43, NULL),
        ('Barbora Krejcikova', 'WTA', 'CZE', false, true, 44, NULL),
        ('Magdalena Frech', 'WTA', 'POL', false, true, 45, NULL),
        ('Janice Tjen', 'WTA', 'INA', false, true, 46, NULL),
        ('Oleksandra Oliynykova', 'WTA', 'UKR', false, true, 47, NULL),
        ('Anhelina Kalinina', 'WTA', 'UKR', false, true, 48, NULL),
        ('Karolina Pliskova', 'WTA', 'CZE', false, true, 49, NULL),
        ('Mayar Sherif', 'WTA', 'EGY', false, true, 50, NULL),
        ('Tamara Korpatsch', 'WTA', 'GER', false, true, 51, NULL),
        ('Zheng Qinwen', 'WTA', 'CHN', false, true, 52, 'QF as qualifier; outside top 50'),
        ('Katerina Siniakova', 'WTA', 'CZE', false, true, 53, NULL),
        ('Katie Boulter', 'WTA', 'GBR', false, true, 54, NULL),
        ('Zhang Shuai', 'WTA', 'CHN', false, true, 55, NULL),
        ('Zeynep Sonmez', 'WTA', 'TUR', false, true, 56, NULL),
        ('Paula Badosa', 'WTA', 'ESP', false, true, 57, NULL),
        ('Jaqueline Cristian', 'WTA', 'ROU', false, true, 58, NULL),
        ('Lilli Tagger', 'WTA', 'AUT', false, true, 59, NULL),
        ('Kimberly Birrell', 'WTA', 'AUS', false, true, 60, NULL),
        ('Tereza Valentova', 'WTA', 'CZE', false, true, 61, NULL),
        ('Lanlana Tararudee', 'WTA', 'THA', false, true, 62, NULL),
        ('Talia Gibson', 'WTA', 'AUS', false, true, 63, NULL),
        ('Camila Osorio', 'WTA', 'COL', false, true, 64, NULL),
        ('Viktorija Golubic', 'WTA', 'SUI', false, true, 65, NULL),
        ('Elena-Gabriela Ruse', 'WTA', 'ROU', false, true, 66, NULL),
        ('Elisabetta Cocciaretto', 'WTA', 'ITA', false, true, 67, NULL),
        ('Caty McNally', 'WTA', 'USA', false, true, 68, NULL),
        ('Anna Bondar', 'WTA', 'HUN', false, true, 69, NULL),
        ('Alycia Parks', 'WTA', 'USA', false, true, 70, NULL),
        ('Ashlyn Krueger', 'WTA', 'USA', false, true, 71, NULL),
        ('McCartney Kessler', 'WTA', 'USA', false, true, 72, NULL),
        ('Kaitlin Quevedo', 'WTA', 'ESP', false, true, 73, NULL),
        ('Panna Udvardy', 'WTA', 'HUN', false, true, 74, NULL),
        ('Magda Linette', 'WTA', 'POL', false, true, 75, NULL),
        ('Petra Marcinko', 'WTA', 'CRO', false, true, 76, NULL),
        ('Kamilla Rakhimova', 'WTA', 'UZB', false, true, 77, NULL),
        ('Katie Volynets', 'WTA', 'USA', false, true, 78, NULL),
        ('Yulia Putintseva', 'WTA', 'KAZ', false, true, 79, NULL),
        ('Antonia Ruzic', 'WTA', 'CRO', false, true, 80, NULL),
        ('Tatjana Maria', 'WTA', 'GER', false, true, 81, NULL),
        ('Alina Korneeva', 'WTA', 'RUS', true, true, 82, NULL),
        ('Wang Xiyu', 'WTA', 'CHN', false, true, 83, NULL),
        ('Hanne Vandewinkel', 'WTA', 'BEL', false, true, 84, NULL),
        ('Daria Kasatkina', 'WTA', 'AUS', false, true, 85, NULL),
        ('Darja Vidmanova', 'WTA', 'CZE', false, true, 86, NULL),
        ('Anna Blinkova', 'WTA', 'FRA', false, true, 87, NULL),
        ('Maria Timofeeva', 'WTA', 'UZB', false, true, 88, NULL),
        ('Mananchaya Sawangkaew', 'WTA', 'THA', false, true, 89, NULL),
        ('Taylor Townsend', 'WTA', 'USA', false, true, 90, 'doubles #2; singles outside top 50'),
        ('Solana Sierra', 'WTA', 'ARG', false, true, 91, NULL),
        ('Renata Zarazua', 'WTA', 'MEX', false, true, 92, NULL),
        ('Jessica Bouzas Maneiro', 'WTA', 'ESP', false, true, 93, NULL),
        ('Taylah Preston', 'WTA', 'AUS', false, true, 94, NULL),
        ('Sinja Kraus', 'WTA', 'AUT', false, true, 95, NULL),
        ('Claire Liu', 'WTA', 'USA', false, true, 96, NULL),
        ('Simona Waltert', 'WTA', 'SUI', false, true, 97, NULL),
        ('Emma Raducanu', 'WTA', 'GBR', false, true, 98, NULL),
        ('Maya Joint', 'WTA', 'AUS', false, true, 99, NULL),
        ('Eva Lys', 'WTA', 'GER', false, true, 100, NULL),
        ('Venus Williams', 'WTA', 'USA', false, true, NULL, 'USO 2026 wildcard at 46; unranked'),
        ('Serena Williams', 'WTA', 'USA', false, true, NULL, 'returned at Wimbledon 2026 (lost 1R); unranked'),
        -- Open Era top 50 by Grand Slam singles titles, then finals (ties at
        -- #50 included), for the headshot picker.
        ('Steffi Graf', 'WTA', 'GER', false, false, NULL, 'Open Era Slam titles: 22 (finals: 31); all-time #2'),
        ('Chris Evert', 'WTA', 'USA', false, false, NULL, 'Open Era Slam titles: 18 (finals: 34); all-time #3'),
        ('Martina Navratilova', 'WTA', 'USA', false, false, NULL, 'Open Era Slam titles: 18 (finals: 32); all-time #4'),
        ('Margaret Court', 'WTA', 'AUS', false, false, NULL, 'Open Era Slam titles: 11 (finals: 12); all-time #5'),
        ('Monica Seles', 'WTA', 'YUG', false, false, NULL, 'Open Era Slam titles: 9 (finals: 13); all-time #6'),
        ('Billie Jean King', 'WTA', 'USA', false, false, NULL, 'Open Era Slam titles: 8 (finals: 12); all-time #7'),
        ('Evonne Goolagong', 'WTA', 'AUS', false, false, NULL, 'Open Era Slam titles: 7 (finals: 18); all-time #8'),
        ('Justine Henin', 'WTA', 'BEL', false, false, NULL, 'Open Era Slam titles: 7 (finals: 12); all-time #10'),
        ('Martina Hingis', 'WTA', 'SUI', false, false, NULL, 'Open Era Slam titles: 5 (finals: 12); all-time #12'),
        ('Arantxa Sanchez Vicario', 'WTA', 'ESP', false, false, NULL, 'Open Era Slam titles: 4 (finals: 12); all-time #14'),
        ('Hana Mandlikova', 'WTA', 'TCH', false, false, NULL, 'Open Era Slam titles: 4 (finals: 8); all-time #16'),
        ('Kim Clijsters', 'WTA', 'BEL', false, false, NULL, 'Open Era Slam titles: 4 (finals: 8); all-time #17'),
        ('Lindsay Davenport', 'WTA', 'USA', false, false, NULL, 'Open Era Slam titles: 3 (finals: 7); all-time #19'),
        ('Angelique Kerber', 'WTA', 'GER', false, false, NULL, 'Open Era Slam titles: 3 (finals: 4); all-time #20'),
        ('Ashleigh Barty', 'WTA', 'AUS', false, false, NULL, 'Open Era Slam titles: 3 (finals: 3); all-time #22'),
        ('Jennifer Capriati', 'WTA', 'USA', false, false, NULL, 'Open Era Slam titles: 3 (finals: 3); all-time #23'),
        ('Virginia Wade', 'WTA', 'GBR', false, false, NULL, 'Open Era Slam titles: 3 (finals: 3); all-time #24'),
        ('Mary Pierce', 'WTA', 'FRA', false, false, NULL, 'Open Era Slam titles: 2 (finals: 6); all-time #25'),
        ('Simona Halep', 'WTA', 'ROU', false, false, NULL, 'Open Era Slam titles: 2 (finals: 5); all-time #26'),
        ('Victoria Azarenka', 'WTA', 'BLR', false, false, NULL, 'Open Era Slam titles: 2 (finals: 5); all-time #27'),
        ('Garbine Muguruza', 'WTA', 'ESP', false, false, NULL, 'Open Era Slam titles: 2 (finals: 4); all-time #28'),
        ('Li Na', 'WTA', 'CHN', false, false, NULL, 'Open Era Slam titles: 2 (finals: 4); all-time #29'),
        ('Svetlana Kuznetsova', 'WTA', 'RUS', false, false, NULL, 'Open Era Slam titles: 2 (finals: 4); all-time #30'),
        ('Amelie Mauresmo', 'WTA', 'FRA', false, false, NULL, 'Open Era Slam titles: 2 (finals: 3); all-time #31'),
        ('Petra Kvitova', 'WTA', 'CZE', false, false, NULL, 'Open Era Slam titles: 2 (finals: 3); all-time #33'),
        ('Tracy Austin', 'WTA', 'USA', false, false, NULL, 'Open Era Slam titles: 2 (finals: 2); all-time #35'),
        ('Jana Novotna', 'WTA', 'CZE', false, false, NULL, 'Open Era Slam titles: 1 (finals: 4); all-time #36'),
        ('Ana Ivanovic', 'WTA', 'SRB', false, false, NULL, 'Open Era Slam titles: 1 (finals: 3); all-time #37'),
        ('Ann Jones', 'WTA', 'GBR', false, false, NULL, 'Open Era Slam titles: 1 (finals: 3); all-time #38'),
        ('Caroline Wozniacki', 'WTA', 'DEN', false, false, NULL, 'Open Era Slam titles: 1 (finals: 3); all-time #39'),
        ('Conchita Martinez', 'WTA', 'ESP', false, false, NULL, 'Open Era Slam titles: 1 (finals: 3); all-time #40'),
        ('Gabriela Sabatini', 'WTA', 'ARG', false, false, NULL, 'Open Era Slam titles: 1 (finals: 3); all-time #41'),
        ('Kerry Melville Reid', 'WTA', 'AUS', false, false, NULL, 'Open Era Slam titles: 1 (finals: 3); all-time #42'),
        ('Mima Jausovec', 'WTA', 'YUG', false, false, NULL, 'Open Era Slam titles: 1 (finals: 3); all-time #43'),
        ('Francesca Schiavone', 'WTA', 'ITA', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #44'),
        ('Marion Bartoli', 'WTA', 'FRA', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #46'),
        ('Marketa Vondrousova', 'WTA', 'CZE', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #47'),
        ('Nancy Richey', 'WTA', 'USA', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #48'),
        ('Samantha Stosur', 'WTA', 'AUS', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #49'),
        ('Sloane Stephens', 'WTA', 'USA', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #50'),
        ('Sofia Kenin', 'WTA', 'USA', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #51'),
        ('Virginia Ruzici', 'WTA', 'ROU', false, false, NULL, 'Open Era Slam titles: 1 (finals: 2); all-time #52'),
        ('Maria Sharapova', 'WTA', 'RUS', false, false, NULL, 'presented USO 2026 trophy but did not play');

    -- Players already listed who were also in the 2010 ATP year-end top 100.
    UPDATE players p SET notes = concat_ws('; ', p.notes, s.note)
    FROM (VALUES
        ('Rafael Nadal', 'ATP year-end #1 in 2010'),
        ('Roger Federer', 'ATP year-end #2 in 2010'),
        ('Novak Djokovic', 'ATP year-end #3 in 2010'),
        ('Andy Murray', 'ATP year-end #4 in 2010'),
        ('Andy Roddick', 'ATP year-end #8 in 2010'),
        ('Marin Cilic', 'ATP year-end #14 in 2010'),
        ('Ivan Ljubicic', 'ATP year-end #17 in 2010'),
        ('John Isner', 'ATP year-end #19 in 2010'),
        ('Stan Wawrinka', 'ATP year-end #21 in 2010'),
        ('Juan Ignacio Chela', 'ATP year-end #38 in 2010'),
        ('Adrian Mannarino', 'ATP year-end #83 in 2010')
    ) AS s (name, note)
    WHERE p.name = s.name;

    -- Players already listed who are also in the Open Era men's top 50 by
    -- Grand Slam singles titles, then finals.
    UPDATE players p SET notes = concat_ws('; ', p.notes, s.note)
    FROM (VALUES
        ('Novak Djokovic', 'Open Era Slam titles: 24 (finals: 38); all-time #1'),
        ('Rafael Nadal', 'Open Era Slam titles: 22 (finals: 30); all-time #2'),
        ('Roger Federer', 'Open Era Slam titles: 20 (finals: 31); all-time #3'),
        ('Carlos Alcaraz', 'Open Era Slam titles: 7 (finals: 8); all-time #11'),
        ('Jannik Sinner', 'Open Era Slam titles: 5 (finals: 7); all-time #14'),
        ('Andy Murray', 'Open Era Slam titles: 3 (finals: 11); all-time #20'),
        ('Stan Wawrinka', 'Open Era Slam titles: 3 (finals: 4); all-time #23'),
        ('Alexander Zverev', 'Open Era Slam titles: 2 (finals: 6); all-time #25'),
        ('Lleyton Hewitt', 'Open Era Slam titles: 2 (finals: 4); all-time #27'),
        ('Sergi Bruguera', 'Open Era Slam titles: 2 (finals: 3); all-time #30'),
        ('Daniil Medvedev', 'Open Era Slam titles: 1 (finals: 6); all-time #34'),
        ('Andy Roddick', 'Open Era Slam titles: 1 (finals: 5); all-time #35'),
        ('Juan Carlos Ferrero', 'Open Era Slam titles: 1 (finals: 3); all-time #39'),
        ('Marin Cilic', 'Open Era Slam titles: 1 (finals: 3); all-time #40')
    ) AS s (name, note)
    WHERE p.name = s.name;

    -- Best 2026 Slam result for each seeded player (QF, SF, F or W).
    WITH results (player, short_name, result) AS (
      VALUES
        ('Jannik Sinner', 'AO', 'SF'),
        ('Jannik Sinner', 'WIM', 'W'),
        ('Alexander Zverev', 'AO', 'SF'),
        ('Alexander Zverev', 'RG', 'W'),
        ('Alexander Zverev', 'WIM', 'F'),
        ('Alexander Zverev', 'USO', 'W'),
        ('Carlos Alcaraz', 'AO', 'W'),
        ('Carlos Alcaraz', 'USO', 'QF'),
        ('Ben Shelton', 'AO', 'QF'),
        ('Ben Shelton', 'USO', 'F'),
        ('Flavio Cobolli', 'RG', 'F'),
        ('Flavio Cobolli', 'WIM', 'QF'),
        ('Frances Tiafoe', 'USO', 'SF'),
        ('Karen Khachanov', 'USO', 'SF'),
        ('Alexander Blockx', 'USO', 'QF'),
        ('Taylor Fritz', 'WIM', 'QF'),
        ('Felix Auger-Aliassime', 'WIM', 'QF'),
        ('Novak Djokovic', 'AO', 'F'),
        ('Novak Djokovic', 'WIM', 'SF'),
        ('Learner Tien', 'AO', 'QF'),
        ('Alex de Minaur', 'AO', 'QF'),
        ('Lorenzo Musetti', 'AO', 'QF'),
        ('Alex Michelsen', 'USO', 'QF'),
        ('Arthur Fery', 'WIM', 'SF'),
        ('Botic van de Zandschulp', 'USO', 'QF'),
        ('Matteo Berrettini', 'RG', 'QF'),
        ('Matteo Arnaldi', 'RG', 'SF'),
        ('Jakub Mensik', 'RG', 'SF'),
        ('Felix Auger-Aliassime', 'RG', 'QF'),
        ('Joao Fonseca', 'RG', 'QF'),
        ('Rafael Jodar', 'RG', 'QF'),
        ('Jan-Lennard Struff', 'WIM', 'QF'),
        ('Elena Rybakina', 'AO', 'W'),
        ('Elena Rybakina', 'USO', 'W'),
        ('Aryna Sabalenka', 'AO', 'F'),
        ('Aryna Sabalenka', 'RG', 'QF'),
        ('Aryna Sabalenka', 'USO', 'F'),
        ('Jessica Pegula', 'AO', 'SF'),
        ('Jessica Pegula', 'WIM', 'QF'),
        ('Jessica Pegula', 'USO', 'SF'),
        ('Coco Gauff', 'AO', 'QF'),
        ('Coco Gauff', 'WIM', 'SF'),
        ('Coco Gauff', 'USO', 'SF'),
        ('Mirra Andreeva', 'RG', 'W'),
        ('Diana Shnaider', 'RG', 'SF'),
        ('Marta Kostyuk', 'RG', 'SF'),
        ('Anna Kalinskaya', 'RG', 'QF'),
        ('Elina Svitolina', 'RG', 'QF'),
        ('Sorana Cirstea', 'RG', 'QF'),
        ('Mirra Andreeva', 'USO', 'QF'),
        ('Linda Noskova', 'WIM', 'W'),
        ('Linda Noskova', 'USO', 'QF'),
        ('Karolina Muchova', 'WIM', 'F'),
        ('Iga Swiatek', 'AO', 'QF'),
        ('Amanda Anisimova', 'AO', 'QF'),
        ('Iva Jovic', 'AO', 'QF'),
        ('Elina Svitolina', 'AO', 'SF'),
        ('Naomi Osaka', 'WIM', 'QF'),
        ('Marta Kostyuk', 'WIM', 'SF'),
        ('Jasmine Paolini', 'WIM', 'QF'),
        ('Elise Mertens', 'WIM', 'QF'),
        ('Emma Navarro', 'USO', 'QF'),
        ('Maja Chwalinska', 'RG', 'F'),
        ('Zheng Qinwen', 'USO', 'QF')
    )
    INSERT INTO tournaments (name, short_name, tour, year, winner, finalists, semifinalists, quarterfinalists)
    SELECT
        slams.name,
        slams.short_name,
        players.tour,
        2026,
        (array_agg(players.id) FILTER (WHERE result = 'W'))[1],
        COALESCE(array_agg(players.id) FILTER (WHERE result IN ('F', 'W')), '{}'),
        COALESCE(array_agg(players.id) FILTER (WHERE result IN ('SF', 'F', 'W')), '{}'),
        array_agg(players.id)
    FROM results
    JOIN players ON players.name = results.player
    JOIN (
      VALUES
        ('Australian Open', 'AO', 1),
        ('Roland Garros', 'RG', 2),
        ('Wimbledon', 'WIM', 3),
        ('US Open', 'USO', 4)
    ) AS slams (name, short_name, sort_order) ON slams.short_name = results.short_name
    GROUP BY slams.name, slams.short_name, slams.sort_order, players.tour
    ORDER BY slams.sort_order, players.tour;
`;

async function main() {
  console.log("seeding...");
  const connectionString = process.argv[2] ?? process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error("Set DATABASE_URL in .env or pass a connection string");
  }
  const client = new Client({ connectionString });

  await client.connect();
  try {
    await client.query(SQL);
  } finally {
    await client.end();
  }
  console.log("done");
}

main();
